AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Description: Calculator

Resources:
  CalculatorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: calculator
      Description: A simple calculator
      CodeUri: "."
      Policies:
        - AWSLambdaBasicExecutionRole
      Runtime: nodejs18.x
      Handler: index.handler
      Architectures:
        - arm64
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - index.ts
        External:
          - "@types/*"
          - aws-lambda
          - chai
          - mocha
        Format: esm
        Minify: false
        OutExtension:
          - .js=.mjs
        Target: "es2020"
